title: Xiaoyu Ma's Blog
author: Xiaoyu Ma
email: 976547109@qq.com
description: > # this means to ignore newlines until "show_exerpts:"
  My blog.
show_excerpts: true # set to true to show excerpts on the homepage
# baseurl: /texture

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Xiaoyu Ma(马晓宇)
  tagline: Student
  date_format: "%b %-d, %Y"
  style: black
  showNav: false
  showPicker: false

  # generate social links in footer
  social_links:
    twitter: /
    github:  derek1998
    linkedIn: in/马晓宇
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed

remote_theme: thelehhman/texture
markdown: kramdown
